package Jframes;

import java.awt.Image;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_departamento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_arbolavl = new javax.swing.JButton();
        btn_dispersa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_activos = new javax.swing.JTextField();
        btn_renta = new javax.swing.JButton();
        btn_activos = new javax.swing.JButton();
        btn_arbolb = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        txt_empresa = new javax.swing.JTextField();
        txt_dep = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbl_matriz = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbl_activosEmpresa = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lbl_activosdepartamento = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lbl_avl = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lbl_rentados = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lbl_b = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nombre de un Departamento:");

        jButton1.setText("Mostrar Activos del Departamento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_arbolavl.setText("AVL del usuario seleccionado");
        btn_arbolavl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_arbolavlActionPerformed(evt);
            }
        });

        btn_dispersa.setText("Matriz Dispersa");
        btn_dispersa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dispersaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre de una empresa: ");

        btn_renta.setText("Activos rentados por el usuario seleccionado");

        btn_activos.setText("Mostrar Activos de la Empresa");
        btn_activos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_activosActionPerformed(evt);
            }
        });

        btn_arbolb.setText("Arbol B");
        btn_arbolb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_arbolbActionPerformed(evt);
            }
        });

        txt_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_depActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btn_dispersa, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_activos, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_activos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_arbolavl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_renta, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_arbolb, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txt_dep, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_dispersa)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_activos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_activos)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(btn_arbolavl)
                        .addGap(22, 22, 22)
                        .addComponent(btn_renta)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_arbolb)))
                .addGap(57, 57, 57))
        );

        jTabbedPane1.addTab("Inicio", jPanel1);

        jScrollPane1.setViewportView(lbl_matriz);

        jTabbedPane1.addTab("Matriz", jScrollPane1);

        jScrollPane2.setViewportView(lbl_activosEmpresa);

        jTabbedPane1.addTab("Activos de la Empresa", jScrollPane2);

        jScrollPane3.setViewportView(lbl_activosdepartamento);

        jTabbedPane1.addTab("Activos del departamento", jScrollPane3);

        jScrollPane4.setViewportView(lbl_avl);

        jTabbedPane1.addTab("AVL del usuario", jScrollPane4);

        jScrollPane5.setViewportView(lbl_rentados);

        jTabbedPane1.addTab("Rentas del Usuario", jScrollPane5);

        jScrollPane6.setViewportView(lbl_b);

        jTabbedPane1.addTab("Arbol B", jScrollPane6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dispersaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dispersaActionPerformed
        // TODO add your handling code here:
        String texto=testwebserver.graficarMatriz();
        File archivo=new File("matriz.txt");
        if(archivo.exists())
        {
            archivo.delete();
        }
        try {
            FileWriter bw=new FileWriter("matriz.txt");
            bw.write(texto);
            bw.close();
            Graficar("matriz");
            Thread.sleep(500);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        Mostrar(lbl_matriz,jTabbedPane1.indexOfTab("Matriz"),"matriz.jpg");
    }//GEN-LAST:event_btn_dispersaActionPerformed

    private void btn_arbolbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_arbolbActionPerformed
        // TODO add your handling code here:
        Mostrar(lbl_b,jTabbedPane1.indexOfTab("Arbol B"),"DIRECCION");
    }//GEN-LAST:event_btn_arbolbActionPerformed

    private void btn_activosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_activosActionPerformed
        // TODO add your handling code here:
        String texto=testwebserver.graficarEmpresa(txt_activos.getText());
        File archivo=new File("empresa.txt");
        if(archivo.exists())
        {
            archivo.delete();
        }
        try {
            FileWriter bw=new FileWriter("empresa.txt");
            bw.write(texto);
            bw.close();
            Graficar("empresa");
            Thread.sleep(500);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        Mostrar(lbl_activosEmpresa,jTabbedPane1.indexOfTab("Activos de la Empresa"),"empresa.jpg");
    }//GEN-LAST:event_btn_activosActionPerformed

    private void btn_arbolavlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_arbolavlActionPerformed
        // TODO add your handling code here:
        String texto=testwebserver.graficarAVL(txt_nombre.getText(),txt_empresa.getText(),txt_dep.getText());
        File archivo=new File("avl.txt");
        if(archivo.exists())
        {
            archivo.delete();
        }
        try {
            FileWriter bw=new FileWriter("avl.txt");
            bw.write(texto);
            bw.close();
            Graficar("avl");
            Thread.sleep(500);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        Mostrar(lbl_avl,jTabbedPane1.indexOfTab("AVL del usuario"),"avl.jpg");
    }//GEN-LAST:event_btn_arbolavlActionPerformed

    private void txt_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_depActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_depActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String texto=testwebserver.graficarDepartamento(txt_departamento.getText());
        File archivo=new File("departamento.txt");
        if(archivo.exists())
        {
            archivo.delete();
        }
        try {
            FileWriter bw=new FileWriter("departamento.txt");
            bw.write(texto);
            bw.close();
            Graficar("departamento");
            Thread.sleep(500);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        Mostrar(lbl_activosdepartamento,jTabbedPane1.indexOfTab("Activos del departamento"),"departamento.jpg");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_activos;
    private javax.swing.JButton btn_arbolavl;
    private javax.swing.JButton btn_arbolb;
    private javax.swing.JButton btn_dispersa;
    private javax.swing.JButton btn_renta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_activosEmpresa;
    private javax.swing.JLabel lbl_activosdepartamento;
    private javax.swing.JLabel lbl_avl;
    private javax.swing.JLabel lbl_b;
    private javax.swing.JLabel lbl_matriz;
    private javax.swing.JLabel lbl_rentados;
    private javax.swing.JTextField txt_activos;
    private javax.swing.JTextField txt_dep;
    private javax.swing.JTextField txt_departamento;
    private javax.swing.JTextField txt_empresa;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables

    private void Mostrar(JLabel lbl, int index, String path) {
        try {
        jTabbedPane1.setSelectedIndex(index);
        ImageIcon fot = new ImageIcon(path);
        Icon icono = new ImageIcon(fot.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT));
        lbl.setIcon(icono);
        lbl.repaint();
        } catch (Exception e) {
            System.out.println("NO SE PUDO CAMBIAR AL INDICE ESPECIFICADO");
        }
    }

    private void Graficar(String matriztxt) throws IOException {
        String nombre = String.valueOf(matriztxt);
          String dotPath = "C:\\Graphviz2.30\\bin\\dot.exe";
          String fileInputPath = matriztxt+".txt";
          String fileOutputPath = matriztxt+".jpg";

          String tParam = "-Tjpg";
          String tOParam = "-o";

          String[] cmd = new String[5];
          cmd[0] = dotPath;
          cmd[1] = tParam;
          cmd[2] = fileInputPath;
          cmd[3] = tOParam;
          cmd[4] = fileOutputPath;

          Runtime rt = Runtime.getRuntime();

          rt.exec(cmd);
    }

}
